---
- block:
  - name: Install Xdebug
    apt:
      name: php-xdebug
      state: latest
      update_cache: true
      cache_valid_time: 3600

  - name: Template the Xdebug configuration file
    template:
      src: xdebug.ini.j2
      dest: /etc/php/7.2/mods-available/xdebug.ini
    notify: reload php7.2-fpm

  - name: Ensure 20-xdebug.ini is present
    file:
      src: /etc/php/7.2/mods-available/xdebug.ini
      dest: /etc/php/7.2/fpm/conf.d/20-xdebug.ini
      state: link
    notify: reload php7.2-fpm
    become: true

  when: xdebug_remote_enable | bool

- name: Disable Xdebug
  file:
    path: /etc/php/7.2/fpm/conf.d/20-xdebug.ini
    state: absent
  when: not xdebug_remote_enable | bool
  notify: reload php7.2-fpm
  become: true

- name: Disable Xdebug CLI
  file:
    path: /etc/php/7.2/cli/conf.d/20-xdebug.ini
    state: absent
