- git:
    repo: '{{git_repository_link}}'
    dest: '{{repository_location}}'
    force: yes
    clone: yes
    version: master

- template:
    src: templates/000-default.conf.j2
    dest: /etc/apache2/sites-enabled/000-default.conf
    backup: yes

- template:
    src: templates/apache2.conf.j2
    dest: /etc/apache2/apache2.conf
    backup: yes

- name: sudo a2enmod rewrite
  command: sudo a2enmod rewrite
  become: yes


- name: restart apache2
  service: name=apache2 state=restarted

- template:
    src: templates/encrypted/.env.j2
    dest: /vagrant/code/.env

#- name: Copy sample config file
#  command: cp {{repository_location}}/.env.example {{repository_location}}/.env creates={{repository_location}}/.env
#  become: yes

#- name: Update laravel .env file
#  lineinfile:
#    dest={{repository_location}}/.env
#    regexp="{{item.regexp}}"
#    line="{{item.line}}"
#  with_items:
#  - {'regexp': "DB_DATABASE=(.)+$", 'line': "DB_DATABASE={{wp_mysql_db}}"}
#  - {'regexp': "DB_USERNAME=(.)+$", 'line': "DB_USERNAME={{wp_mysql_user}}"}
#  - {'regexp': "DB_PASSWORD=(.)+$", 'line': "DB_PASSWORD={{wp_mysql_password}}"}
#  - {'regexp': "DB_PASSWORD=(.)+$", 'line': "DB_PASSWORD={{wp_mysql_password}}"}
#  become: yes


# Installs package globally
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

# Run this command manually
#- composer:
#    command: install
#    working_dir: "{{repository_location}}"

#chdir - is the directory for where to run this command from
- name: generage encryption key
  command: php artisan key:generate chdir={{repository_location}}
  become: yes

- name: migrate laravel
  command: php artisan migrate --force chdir={{repository_location}}

- template:
    src: templates/seeders/AuthClientsTableSeeder.php.j2
    dest: /vagrant/code/database/seeds/AuthClientsTableSeeder.php

#- name: migrate seed
#  command: php artisan db:seed chdir={{repository_location}}

- name: Install nodeJS
  apt:
    name: nodejs
    state: present

- name: Install npm
  apt:
    name: npm
    state: present

# Run this command manually
#- name: Install npm modules
#  shell: npm install
#  args:
#    chdir: "{{ repository_location }}"

# Run this command manually
#- name: run build
#  shell: npm run build
#  args:
#    chdir: "{{ repository_location }}"